name: test

services:
  loki:
    image: grafana/loki:2.8.2
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
    command: 
      - "--config.file=/etc/loki/config.yml"

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yaml:ro
      - log_storage:/var/log
    command:
      - --config.file=/etc/promtail/config.yaml

  flog:
    image: mingrammer/flog:0.4.3
    command:
      - --loop
      - --format=json
      - --number=1 
      - --delay=1s
      - --type=log
      - --output=/var/log/flog.log
      - --overwrite         
    volumes:
      - log_storage:/var/log

  curl:
    image: curlimages/curl
    volumes:
      - ./curl:/tests/curl
    entrypoint: 
      - sh
      - /tests/curl/entrypoint.sh

networks:
  test_network:
  default:
    name: test_network

volumes:
  log_storage: