clients:
  - url: http://test-loki-1:3100/loki/api/v1/push

scrape_configs:
  - job_name: flog_scrape 
    static_configs:
    - targets:
        - localhost
      labels:
        __path__: /var/log/flog.log
